// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQb9929_YOkgqfkxDZJ9O0COp3Q0Gn5kY',
    appId: '1:51570413013:web:a1b1426794af6e4f48c15c',
    messagingSenderId: '51570413013',
    projectId: 'fir-testing-4647b',
    authDomain: 'fir-testing-4647b.firebaseapp.com',
    storageBucket: 'fir-testing-4647b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHfu2FvTBg_rueXscf0oZMtECBYC7uzuc',
    appId: '1:51570413013:android:0f7479f41c79428748c15c',
    messagingSenderId: '51570413013',
    projectId: 'fir-testing-4647b',
    storageBucket: 'fir-testing-4647b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMnniTrG4WMaAvJ3jpB25_QJyh1mxmzg',
    appId: '1:51570413013:ios:80218470218b8d5248c15c',
    messagingSenderId: '51570413013',
    projectId: 'fir-testing-4647b',
    storageBucket: 'fir-testing-4647b.appspot.com',
    iosBundleId: 'com.ranjeet.testFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnMnniTrG4WMaAvJ3jpB25_QJyh1mxmzg',
    appId: '1:51570413013:ios:439d18092c89b13048c15c',
    messagingSenderId: '51570413013',
    projectId: 'fir-testing-4647b',
    storageBucket: 'fir-testing-4647b.appspot.com',
    iosBundleId: 'com.example.testFirestore.RunnerTests',
  );
}
